services:

  data-api:
    build: ./data_api
    ports:
      - "8001:7860"
    env_file: .env

  model-api:
    build: ./model_api
    ports:
      - "8002:7860"
    env_file: .env

  dashboard:
    build: ./dashboard
    ports:
      - "8501:7860"
    env_file: .env
    depends_on:
      - data-api
      - model-api

  airflow:
    build: ./airflow
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URL}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "meteo-mlops-secret-key"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /opt/airflow
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      DATA_API_BASE_URL: http://data-api:7860
      MODEL_API_BASE_URL: http://model-api:7860
    volumes:
      - ./dags:/opt/airflow/dags
      - ./train:/opt/airflow/train
      - ./utils:/opt/airflow/utils
      - ./monitoring:/opt/airflow/monitoring
      - ./etl.py:/opt/airflow/etl.py
    command: standalone
    depends_on:
      - data-api
      - model-api
    profiles:
      - airflow

  etl:
    build: .
    env_file: .env
    environment:
      DATA_API_BASE_URL: http://data-api:7860
      MODEL_API_BASE_URL: http://model-api:7860
    depends_on:
      - data-api
      - model-api
    profiles:
      - etl
